name: Build Go App

on:
  push:
    branches:
      - '**'   # läuft auf JEDEM Branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build main.go
        run: |
          go mod download
          go build -v -o app main.go